name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i -g --force corepack@latest && corepack enable

      - name: Install dependencies
        run: npx nypm@latest i

        # Run linting
      - name: Lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Enable corepack for pnpm
      - run: npm i -g --force corepack@latest && corepack enable

      # Install dependencies
      - name: Install dependencies
        run: npx nypm@latest i

        # Prepare the environment
      - name: Playground prepare
        run: pnpm dev:prepare

        # Run tests
      - name: Test
        run: pnpm test
